// export let playerUnits = [
//   {
//     name: 'unit1',
//     id: 1,
//     currentNode: {
//       x: 10,
//       y: 10
//     },
//     x: 10,
//     y: 10,
//     health: 100,
//     controlBy: 'player',
//     speed: 5,
//     armour: 7,
//     range: 34,
//     meleeDamage: 10,
//     missileDamage: 0,
//     discipline: 71,
//     morale: 78,
//     condition: 100
//   },
//   {
//     name: 'unit2',
//     id: 2,
//     currentNode: {
//       x: 200,
//       y: 20
//     },
//     x: 200,
//     y: 20,
//     health: 70,
//     controlBy: 'player',
//     speed: 15,
//     armour: 3,
//     range: 3,
//     meleeDamage: 4,
//     missileDamage: 2,
//     discipline: 6,
//     morale: 20,
//     condition: 10
//   },
//   {
//     name: 'unit3',
//     id: 3,
//     currentNode: {
//       x: 300,
//       y: 400
//     },
//     x: 300,
//     y: 400,
//     health: 11,
//     controlBy: 'player',
//     speed: 5,
//     armour: 3,
//     range: 3,
//     meleeDamage: 2,
//     missileDamage: 1,
//     discipline: 2,
//     morale: 34,
//     condition: 80
//   }
// ];
//
// export let controlByComputerUnits:any[] = [
//   {
//     name: 'unit1',
//     type: 'spearmen',
//     id: 4,
//     currentNode: {
//       x: 10,
//       y: 10
//     },
//     x: 10,
//     y: 10,
//     isFighting: true,
//     health: 40,
//     controlBy: 'computer',
//     speed: 3,
//     armour: 4,
//     range: 4,
//     meleeDamage: 12,
//     missileDamage: 2,
//     discipline: 87,
//     morale: 72,
//     condition: 99,
//     task: 'exploration',
//     unitToProtect: {id: 6},
//     isUnitUnderProtection: false,
//     unitToHelp: {},
//     isUnitNeedHelp: false,
//     beCloseTo: [],
//   },
//   {
//     name: 'unit2',
//     type: 'spearmen',
//     id: 5,
//     currentNode: {
//       x: 200,
//       y: 20
//     },
//     x: 200,
//     y: 20,
//     isFighting: false,
//     health: 63,
//     controlBy: 'computer',
//     speed: 15,
//     armour: 5,
//     range: 2,
//     meleeDamage: 6,
//     missileDamage: 3,
//     discipline: 16,
//     morale: 30,
//     condition: 76,
//     task: 'occupation',
//     unitToProtect: {},
//     isUnitUnderProtection: false,
//     unitToHelp: {},
//     isUnitNeedHelp: false,
//     beCloseTo: [],
//   },
//   {
//     name: 'unit3',
//     type: 'skirmishers',
//     id: 6,
//     currentNode: {
//       x: 300,
//       y: 400
//     },
//     x: 300,
//     y: 400,
//     isFighting: false,
//     health: 56,
//     controlBy: 'computer',
//     speed: 14,
//     armour: 6,
//     range: 1,
//     meleeDamage: 23,
//     missileDamage: 15,
//     discipline: 20,
//     morale: 22,
//     condition: 56,
//     task: '',
//     unitToProtect: {},
//     isUnitUnderProtection: false,
//     unitToHelp: {},
//     isUnitNeedHelp: false,
//     beCloseTo: [],
//   }
// ];
